"use client";

import { useCallback, useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AdminAnalytics, api } from "@/lib/api";

export default function AdminDashboard({ onBack }: { onBack: () => void }) {
  const [data, setData] = useState<AdminAnalytics | null>(null);
  const [error, setError] = useState("");
  const [comparison, setComparison] = useState<string[]>([]);
  const load = useCallback(() => api.analytics().then(setData).catch((e) => setError(e.message)), []);
  useEffect(() => { load(); }, [load]);
  async function blacklist(id: string, value: boolean) { await api.blacklist(id, value); await load(); }
  async function remove(id: string, label: string) { if (window.confirm(`Delete ${label} and all enrollment sessions?`)) { await api.deleteProfile(id); await load(); } }
  if (!data) return <div className="p-10 text-muted">{error || "loading admin analytics…"}</div>;
  const bars = data.profiles.map((profile) => ({ name: profile.label, samples: profile.enrollment_count }));
  const ablationBars = data.experiment ? Object.entries(data.experiment.ablations).map(([name, metrics]) => ({ name: name.replaceAll("_", " "), accuracy: Math.round(metrics.accuracy * 100), auc: Math.round(metrics.verification_auc * 100) })) : [];
  const effectiveComparison = comparison.length ? comparison : data.profile_cards.slice(0, 2).map((card) => card.id);
  const selectedCards = data.profile_cards.filter((card) => effectiveComparison.includes(card.id));
  const ratingNames = ["Typing speed", "Rhythm", "Precision", "Cursor control", "Agility", "Steadiness"];
  const radarData = ratingNames.map((attribute) => ({ attribute, ...Object.fromEntries(selectedCards.map((card) => [card.label, card.ratings[attribute]])) }));
  const colors = ["var(--cyan)", "var(--amber)", "var(--danger)", "#9f8cff"];
  const historyLength = Math.max(0, ...selectedCards.map((card) => card.history.length));
  const wpmTrend = Array.from({ length: historyLength }, (_, index) => ({ session: index + 1, ...Object.fromEntries(selectedCards.map((card) => [card.label, card.history[index]?.wpm ?? null])) }));
  const clickTrend = Array.from({ length: historyLength }, (_, index) => ({ session: index + 1, ...Object.fromEntries(selectedCards.map((card) => [card.label, card.history[index]?.click_error_px ?? null])) }));
  function toggleComparison(id: string) {
    const current = effectiveComparison;
    if (current.includes(id)) setComparison(current.filter((value) => value !== id));
    else if (current.length < 4) setComparison([...current, id]);
  }
  return (
    <div className="flex-1 px-6 py-8 overflow-y-auto"><div className="max-w-6xl mx-auto fade-up">
      <button onClick={onBack} className="text-xs text-muted font-mono-tight mb-6 hover:text-text">← home</button>
      <div className="flex flex-wrap justify-between gap-4 items-end mb-8"><div><div className="font-mono-tight text-xs uppercase tracking-[0.3em] text-danger mb-2">admin</div><h1 className="text-3xl font-semibold">Behavior intelligence</h1></div><div className="text-xs text-muted max-w-md">{data.model.strategy}</div></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-8">{Object.entries(data.summary).map(([label, value]) => <div key={label} className="bg-surface border border-border rounded-xl p-4"><div className="text-2xl font-mono-tight">{value}</div><div className="text-xs text-muted mt-1">{label.replaceAll("_", " ")}</div></div>)}</div>
      <div className="grid lg:grid-cols-2 gap-5 mb-8">
        <section className="bg-surface border border-border rounded-xl p-5"><h2 className="font-mono-tight text-xs uppercase tracking-widest mb-4">enrollment depth</h2><ResponsiveContainer width="100%" height={260}><BarChart data={bars}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis tick={{fill:"var(--muted)",fontSize:10}} allowDecimals={false}/><Tooltip/><Bar dataKey="samples" fill="var(--amber)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section>
        <section className="bg-surface border border-border rounded-xl p-5"><h2 className="font-mono-tight text-xs uppercase tracking-widest mb-4">profile similarity matrix</h2><div className="overflow-auto"><table className="text-[10px] font-mono-tight border-separate border-spacing-1"><thead><tr><th></th>{data.similarity_labels.map((label) => <th key={label} className="px-1 text-muted max-w-14 truncate">{label}</th>)}</tr></thead><tbody>{data.similarity_matrix.map((row, i) => <tr key={data.similarity_labels[i]}><th className="pr-2 text-right text-muted">{data.similarity_labels[i]}</th>{row.map((value, j) => <td key={j} title={`${value ?? "n/a"}%`} className="w-9 h-9 text-center rounded" style={{background:value == null ? "var(--surface-2)" : `rgba(94,224,196,${Math.max(0.08,value/100)})`,color:value && value > 65 ? "var(--bg)" : "var(--text)"}}>{value == null ? "–" : Math.round(value)}</td>)}</tr>)}</tbody></table></div></section>
      </div>
      <section className="bg-surface border border-border rounded-xl p-5 mb-8">
        <div className="flex flex-wrap justify-between items-start gap-4 mb-5"><div><div className="font-mono-tight text-xs uppercase tracking-widest text-cyan">versus mode</div><h2 className="text-2xl font-semibold mt-2">Profile character comparison</h2><p className="text-sm text-muted mt-1">Select up to four profiles. Ratings are percentiles among the current roster; raw measurements are shown below.</p></div><div className="flex flex-wrap gap-2 max-w-xl">{data.profile_cards.map((card) => <button key={card.id} onClick={() => toggleComparison(card.id)} disabled={!effectiveComparison.includes(card.id) && effectiveComparison.length >= 4} className={`px-3 py-2 rounded-lg border text-xs transition disabled:opacity-30 ${effectiveComparison.includes(card.id) ? "border-cyan bg-cyan/10 text-cyan" : "border-border text-muted hover:text-text"}`}>{card.label}</button>)}</div></div>
        {selectedCards.length ? <>
          <div className="grid lg:grid-cols-[1.1fr_1fr] gap-6 items-center">
            <ResponsiveContainer width="100%" height={390}><RadarChart data={radarData} outerRadius="72%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="attribute" tick={{fill:"var(--muted)",fontSize:11}}/><PolarRadiusAxis angle={30} domain={[0,100]} tick={{fill:"var(--muted)",fontSize:9}}/>{selectedCards.map((card, index) => <Radar key={card.id} name={card.label} dataKey={card.label} stroke={colors[index]} fill={colors[index]} fillOpacity={0.12} strokeWidth={2}/>) }<Legend/></RadarChart></ResponsiveContainer>
            <div className="grid sm:grid-cols-2 gap-3">{selectedCards.map((card, index) => <div key={card.id} className="bg-surface-2 border border-border rounded-xl p-4 relative overflow-hidden"><div className="absolute -right-1 -top-5 font-mono-tight text-8xl opacity-[0.06]" style={{color:colors[index]}}>{card.rank}</div><div className="flex justify-between items-start"><div><div className="font-semibold text-lg">{card.label}</div><div className="text-xs text-muted">{card.enrollment_count} session{card.enrollment_count === 1 ? "" : "s"}</div></div><div className="w-11 h-11 rounded-lg flex items-center justify-center font-mono-tight text-xl text-bg" style={{background:colors[index]}}>{card.rank}</div></div><div className="font-mono-tight text-3xl mt-5">{card.overall}<span className="text-xs text-muted"> / 100</span></div><div className="text-xs text-muted">overall roster rating</div>{card.missing_ratings.length > 0 && <div className="text-[10px] text-amber mt-3">Neutral rating used for missing: {card.missing_ratings.join(", ")}</div>}</div>)}</div>
          </div>
          <div className="overflow-auto mt-6"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left text-xs text-muted border-b border-border"><th className="py-3 pr-4">real measurement</th>{selectedCards.map((card) => <th key={card.id} className="py-3 px-3">{card.label}</th>)}</tr></thead><tbody>{[
            ["Typing speed", "wpm", " WPM"], ["Key dwell", "dwell_ms", " ms"], ["Key flight", "flight_ms", " ms"], ["Inter-key interval", "iki_ms", " ms"], ["Backspace rate", "backspace_rate", "%", 100], ["Mouse speed", "mouse_speed_pxs", " px/s"], ["Click error", "click_error_px", " px"], ["Target travel", "target_time_ms", " ms"], ["Tracking error", "tracking_error_px", " px"], ["Tremor", "tremor_px", " px"], ["Drag duration", "drag_duration_ms", " ms"], ["Drag success", "drag_success_rate", "%", 100],
          ].map(([label, key, suffix, multiplier]) => <tr key={String(key)} className="border-b border-border/60"><td className="py-3 pr-4 text-muted">{label}</td>{selectedCards.map((card) => { const value = card.metrics[String(key)]; return <td key={card.id} className="py-3 px-3 font-mono-tight">{value == null ? <span className="text-muted">not available</span> : `${(Number(value) * Number(multiplier || 1)).toFixed(1)}${suffix}`}</td>; })}</tr>)}</tbody></table></div>
          <div className="grid lg:grid-cols-2 gap-5 mt-7"><div><h3 className="font-mono-tight text-xs uppercase tracking-widest text-muted mb-3">WPM across enrollments</h3><ResponsiveContainer width="100%" height={220}><LineChart data={wpmTrend}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="session" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis tick={{fill:"var(--muted)",fontSize:10}}/><Tooltip/>{selectedCards.map((card,index) => <Line key={card.id} type="monotone" dataKey={card.label} stroke={colors[index]} strokeWidth={2} connectNulls dot={{r:4}}/>)}</LineChart></ResponsiveContainer></div><div><h3 className="font-mono-tight text-xs uppercase tracking-widest text-muted mb-3">Click error across enrollments</h3><ResponsiveContainer width="100%" height={220}><LineChart data={clickTrend}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="session" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis tick={{fill:"var(--muted)",fontSize:10}} unit="px"/><Tooltip/>{selectedCards.map((card,index) => <Line key={card.id} type="monotone" dataKey={card.label} stroke={colors[index]} strokeWidth={2} connectNulls dot={{r:4}}/>)}</LineChart></ResponsiveContainer></div></div>
        </> : <div className="text-muted text-sm py-10 text-center">Select at least one profile to compare.</div>}
      </section>
      {data.experiment && <section className="bg-surface border border-border rounded-xl p-5 mb-8">
        <div className="flex flex-wrap justify-between gap-4 mb-5"><div><h2 className="font-mono-tight text-xs uppercase tracking-widest">training benchmark</h2><p className="text-xl mt-2">{data.experiment.best_model.replaceAll("_", " ")} · {Math.round(data.experiment.best_metrics.accuracy * 100)}% held-window accuracy</p></div><div className="text-xs text-muted">SVM C={data.experiment.tuned_svm.C}, gamma={data.experiment.tuned_svm.gamma}<br/>Neural validation {Math.round(data.experiment.neural.best_validation_accuracy * 100)}%</div></div>
        <div className="grid lg:grid-cols-[1fr_1.2fr] gap-5 items-center"><div className="grid grid-cols-2 gap-3"><div className="bg-surface-2 rounded-lg p-4"><div className="font-mono-tight text-xl">{data.experiment.best_metrics.verification_auc.toFixed(4)}</div><div className="text-xs text-muted">verification AUC</div></div><div className="bg-surface-2 rounded-lg p-4"><div className="font-mono-tight text-xl">{(data.experiment.best_metrics.eer * 100).toFixed(2)}%</div><div className="text-xs text-muted">equal-error rate</div></div><p className="col-span-2 text-xs text-danger/90">{data.experiment.warning}</p></div><ResponsiveContainer width="100%" height={220}><BarChart data={ablationBars}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis domain={[0,100]} tick={{fill:"var(--muted)",fontSize:10}}/><Tooltip/><Bar dataKey="accuracy" fill="var(--cyan)" radius={[4,4,0,0]}/><Bar dataKey="auc" fill="var(--amber)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      </section>}
      <section className="bg-surface border border-border rounded-xl overflow-hidden"><div className="p-5 border-b border-border"><h2 className="font-mono-tight text-xs uppercase tracking-widest">profiles</h2></div><div className="divide-y divide-border">{data.profiles.map((profile) => <div key={profile.id} className="p-4 flex flex-wrap items-center gap-4"><div className="flex-1 min-w-40"><div className={profile.blacklisted ? "line-through text-muted" : ""}>{profile.label}</div><div className="text-xs text-muted mt-1">{profile.enrollment_count} enrollment{profile.enrollment_count === 1 ? "" : "s"} · {profile.last_enrollment ? new Date(profile.last_enrollment).toLocaleDateString() : "never"}</div></div><button onClick={() => blacklist(profile.id, !profile.blacklisted)} className={`px-3 py-2 rounded text-xs font-mono-tight ${profile.blacklisted ? "bg-cyan/15 text-cyan" : "bg-amber/15 text-amber"}`}>{profile.blacklisted ? "restore" : "blacklist"}</button><button onClick={() => remove(profile.id, profile.label)} className="px-3 py-2 rounded text-xs font-mono-tight bg-danger/15 text-danger">delete</button></div>)}</div></section>
      <div className="mt-6 text-xs text-muted">Model {data.model.version.slice(0,19)} · {data.model.svm_trained ? "SVM active" : "centroid mode"} · neural {data.model.neural_ready ? "ready" : "waiting for repeated sessions"}</div>
    </div></div>
  );
}
