"""Phase 0 initial schema: profiles, sessions, verification_events,
review_samples, model_versions, embeddings, profile_templates.

This migration is hand-written rather than autogenerated (there is no live
database available in the environment producing it to diff against), but it
mirrors `behaveguard.db.models.Base.metadata` field-for-field. Re-run
`alembic check` (or diff manually) against a real database before relying on
autogenerate for future revisions, to confirm the two haven't drifted.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-17
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 128


def upgrade() -> None:
    # pgvector must be enabled before any VECTOR columns are created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("label", sa.String(80), nullable=False),
        sa.Column("blacklisted", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # Case-insensitive uniqueness on label — equivalent to SQLite's
    # `UNIQUE ... COLLATE NOCASE` from the v1 prototype.
    op.execute(
        "CREATE UNIQUE INDEX ux_profiles_label_lower ON profiles (lower(label))"
    )

    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(40), nullable=False),
        sa.Column("collected_at", sa.String(64), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("idx_sessions_profile", "sessions", ["profile_id"])

    op.create_table(
        "verification_events",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("mode", sa.String(10), nullable=False),
        sa.Column(
            "claimed_profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("candidates", postgresql.JSONB, nullable=False),
        sa.Column("result", postgresql.JSONB, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "review_samples",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "verification_event_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("verification_events.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("mode", sa.String(10), nullable=False),
        sa.Column(
            "claimed_profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "predicted_profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("candidate_ids", postgresql.JSONB, nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column("result", postgresql.JSONB, nullable=False),
        sa.Column("feedback_correct", sa.Boolean, nullable=True),
        sa.Column(
            "true_profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("status", sa.String(20), nullable=False, server_default="awaiting_feedback"),
        sa.Column(
            "promoted_session_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('awaiting_feedback','pending','approved','rejected')",
            name="ck_review_samples_status",
        ),
    )
    op.create_index("idx_review_samples_status", "review_samples", ["status", "created_at"])

    op.create_table(
        "model_versions",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("kind", sa.String(40), nullable=False),
        sa.Column("artifact_uri", sa.String(500), nullable=True),
        sa.Column("config_fingerprint", sa.String(128), nullable=True),
        sa.Column("dataset_fingerprint", sa.String(128), nullable=True),
        sa.Column("metrics", postgresql.JSONB, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="candidate"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('candidate','active','retired')", name="ck_model_versions_status"),
    )

    op.create_table(
        "embeddings",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "model_version_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("model_versions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("modality", sa.String(20), nullable=False, server_default="fused"),
        sa.Column("vector", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("quality_score", sa.Float, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    # HNSW index for approximate nearest-neighbor cosine search. Not queried
    # yet in Phase 0 (nothing populates this table until a later phase), but
    # created now so the index build doesn't compete with production traffic
    # later.
    op.execute(
        "CREATE INDEX idx_embeddings_vector_cosine ON embeddings "
        "USING hnsw (vector vector_cosine_ops)"
    )

    op.create_table(
        "profile_templates",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "profile_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "model_version_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("model_versions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("centroid", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("dispersion", sa.Float, nullable=True),
        sa.Column("sample_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("threshold_override", sa.Float, nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("profile_id", "model_version_id", name="uq_profile_template_version"),
    )


def downgrade() -> None:
    op.drop_table("profile_templates")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_vector_cosine")
    op.drop_table("embeddings")
    op.drop_table("model_versions")
    op.drop_index("idx_review_samples_status", table_name="review_samples")
    op.drop_table("review_samples")
    op.drop_table("verification_events")
    op.drop_index("idx_sessions_profile", table_name="sessions")
    op.drop_table("sessions")
    op.execute("DROP INDEX IF EXISTS ux_profiles_label_lower")
    op.drop_table("profiles")
    op.execute("DROP EXTENSION IF EXISTS vector")
